### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'shape'

### ISSUE THREAD

**Issue by danish-rnd** [LynnHaDo/Checkbox-Detection#5]
Hi 
Thanks for this amazing project. Im facing this issue while running your code. Also can you please identify the ultralytics version that you used?
`Traceback (most recent call last):
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "d:\checkbox\checkbox-detection\app.py", line 56, in detect
    cls_results = CLASSIFICATION_MODEL.predict(source=box, conf=0.5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 274, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 204, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 275, in stream_inference
    im = self.preprocess(im0s)
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\models\yolo\classify\predict.py", line 46, in preprocess
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\models\yolo\classify\predict.py", line 46, in <listcomp>
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
AttributeError: 'Image' object has no attribute 'shape'`

**Comment by LynnHaDo** [comment]
Hi,

Thank you for your interest in my project! This seems to be a common issue, so I will take a closer look at this. On the other hand, the ultralytics version I used is 8.0.136.

**Comment by LynnHaDo** [comment]
Hi @danish-rnd

I was looking around to see where the issue is, and it might be because of the version incompatibility between mine and yours. So I propose 2 suggestions:

1. This seems to be a recent issue with ultralytics' classification model, which you can find the [thread here](https://github.com/ultralytics/ultralytics/issues/7473) for solutions.

2. Change ultralytics to version 8.0.153 (sorry for the previous response—I should update that!)

Let me know if it addresses your issue!

**Comment by danish-rnd** [comment]
I have installed the libraries that you mentioned. Now im getting new type of error 
`Traceback (most recent call last):
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "d:\checkbox\checkbox-detection\app.py", line 58, in detect
    cls_results = CLASSIFICATION_MODEL.predict(source=box, conf=0.5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 246, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 197, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 249, in stream_inference
    im = self.preprocess(im0s)
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\models\yolo\classify\predict.py", line 19, in preprocess
    img = torch.stack([self.transforms(im) for im in img], dim=0)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\ultralytics\models\yolo\classify\predict.py", line 19, in <listcomp>
    img = torch.stack([self.transforms(im) for im in img], dim=0)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\syed.danish\AppData\Local\anaconda3\Lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
ValueError: too many values to unpack (expected 2)`

**Comment by LynnHaDo** [comment]
Hi @danish-rnd,

It's unclear to me whether this error is caused by an error in my code, or some other version incompatibility. Have you tried the first suggestion in my previous reply?
