### ISSUE TITLE
Error Encountered with Classification Model on Boxes Extracted by Detection Model

### ISSUE THREAD

**Issue by Nomiluks** [LynnHaDo/Checkbox-Detection#7]
I liked the work you have done.

Encountered an error while attempting to utilize the `CLASSIFICATION_MODEL` on boxes extracted by the `DETECTION_MODEL`. While the `DETECTION_MODEL` functions correctly, the `CLASSIFICATION_MODEL` fails to produce the expected results.

Steps to Reproduce:

1. Utilize the DETECTION_MODEL to extract boxes from an image.
2. Apply the CLASSIFICATION_MODEL to classify the extracted boxes.
3. Observe the error detailed below.

Code:
```
cls_results = CLASSIFICATION_MODEL.predict(source=box, conf=0.5)  # <------------ Here I am getting an error
probs = cls_results[0].probs  # cls prob, (num_class, )
classification_class = list(BOX_COLORS)[2 - int(probs.top1)]
classification_class_conf = round(probs.top1conf.item(), 2)

cls = (
    classification_class if classification_class_conf > 0.9 else detection_class
)

**Error:**

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscode/.local/lib/python3.11/site-packages/ultralytics/engine/model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in preprocess
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py", line 46, in <listcomp>
    [self.transforms(Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))) for im in img], dim=0
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: shape
```

**Comment by LynnHaDo** [comment]
Hi @Nomiluks,

Thank you for your interest in this project. Someone actually raised this problem before, and it seems to stem from some conflicts between the old and new versions of Ultralytics YOLOv8 that cause the classification models to behave differently in different versions. I suspect that [this](https://github.com/ultralytics/ultralytics/issues/7473) is the issue you are encountering. 

Hope that helps!

**Comment by Nomiluks** [comment]
Thank you for clarification, I will look into it.
